[package]
name = "rustgas"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serde = "1.0"
serde_json = "1.0"
aga_tables = { git = "https://github.com/renatoexpert/aga_tables" }
